Bar 74 run all fl nodes on one cluster node
genxnetwork/uk-biobank pull request #24
Opened 2022-04-14 08:59 UTC by alex-medvedev-msc

1. Everything on one node
2. FL models now imported from nn.models
3. FL test dataset evaluation

2022-04-14 10:06 UTC, satyarth requested changes

2022-04-14 10:06 UTC, satyarth commented on src/fl/datasets/lightning.py
>  class DataModule(LightningDataModule):
Use datamodule from `nn` directory

2022-04-14 13:20 UTC, dkolobok approved these changes

2022-04-14 13:20 UTC, dkolobok commented on src/fl/federation/client.py
> +        try:
if try-except are necessary, please write a comment that explains why

2022-04-18 10:45 UTC, satyarth approved these changes

2022-04-19 08:09 UTC, merged